{% set name = "pynput" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e50b1a0ab86847e87e58f6d1993688b9a44f9f4c88d4712315ea8eb552ef828

build:
  number: 1

requirements:
  host:
    - python
    - pip
    - six 
    - setuptools-lint >=0.5
    - sphinx
    - wrapt
  run:
    - python
    - six
    - setuptools-lint >=0.5
    - sphinx
    - wrapt
    - python-xlib
    - pyobjc-core 7.3               # [osx]
    - pyobjc-framework-cocoa 7.3    # [osx]
    - pyobjc-framework-quartz 7.3   # [osx]

test:
  commands:
    - bash -c "DISPLAY=:1 python -c 'import pynput'"

about:
  home: https://github.com/moses-palmer/pynput
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE # no license file packaged with source, issue here: https://github.com/moses-palmer/pynput/issues/241
  summary: This library allows you to control and monitor input devices.
  doc_url: https://pynput.readthedocs.io/en/latest/
  dev_url: https://github.com/moses-palmer/pynput

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
